version: '3.8'
services:
  app:
    build: ./web-app
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/
      - MACHINE_LEARNING_CLIENT_URL=http://client:5002
    depends_on:
      - mongo
      - client
    networks:
      - app-network
   
  client:
    build: ./machine-learning-client
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    networks:
      - app-network
    # Uncomment the next line if your client requires camera access
    # devices:
    #   - "/dev/video0:/dev/video0"

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
