version: '3.8'
services:
  app:
    build: ./web-app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/    
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build: ./machine-learning-client
    depends_on:
      - app
    networks:
      - app-network

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
