name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    - name: Run tests
      run: |
        pipenv run pytest
    - name: Build and Push Docker
      run: |
        # Add Docker build and push commands here
